<a href="https://colab.research.google.com/github/shrey-shetty/v/blob/main/3_Split_Columns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
@author: Ashish Chouhan
Split column further
"""

# Import Libraries
import pandas as pd
import numpy as np

# Read the TalendDemoFile1.txt file using pandas.read_table function and populate the records into an Input Dataframe
# Optional: specify the field separator present in file also define the Schema for the file
df_input = pd.read_table('TalendDemoFile1.txt', delimiter = ';',
                         header = 0,
                         dtype={'emp_no': np.int64, 'emp_name': str, 'emp_skills': str})

df_input

   emp_no emp_name            emp_skills
0     101  Johnson          Java,SQL,C++
1     102   Sachin       Oracle,HTML,JSP
2     103  Micheal  Talend,Ajax,JSP,HTML

In [ ]:
# Delete the record having NaN or Null Values for any of the fields present in the input dataframe
# TODO: Add your code here
df_input = df_input.dropna()
df_input

   emp_no emp_name            emp_skills
0     101  Johnson          Java,SQL,C++
1     102   Sachin       Oracle,HTML,JSP
2     103  Micheal  Talend,Ajax,JSP,HTML

Requirement is to split the Employee Skill Column further into different column having only one skill in it

In [ ]:
# Split the column Employee Skills (emp_skills) present in input dataframe (df_input) into 4 different
# employee skill column based on field separator ',' and populate it into a new dataframe
df_middle = df_input["emp_skills"].str.split(",", n = 3, expand = True)

df_middle

        0     1    2     3
0    Java   SQL  C++  None
1  Oracle  HTML  JSP  None
2  Talend  Ajax  JSP  HTML

In [ ]:
# Create a Seperate Employee Skills column in Input Dataframe (df_input) from df_middle data frame
df_input["Employee Skills 1"]= df_middle[0]
df_input["Employee Skills 2"]= df_middle[1]
df_input["Employee Skills 3"]= df_middle[2]
df_input["Employee Skills 4"]= df_middle[3]

df_input

,emp_no,emp_name,emp_skills,Employee Skills 1,Employee Skills 2,Employee Skills 3,Employee Skills 4
0,101,Johnson,"Java,SQL,C++",Java,SQL,C++,None
1,102,Sachin,"Oracle,HTML,JSP",Oracle,HTML,JSP,None
2,103,Micheal,"Talend,Ajax,JSP,HTML",Talend,Ajax,JSP,HTML

# Formatting of Dataframe

In [ ]:
# Delete the old column Employee Skills (emp_skills) from the input dataframe (df_input)
# Since old column is splitted into 4 new employee skill column
# TODO: Add your code here
df_input= df_input.drop(columns='emp_skills')
df_input

,emp_no,emp_name,Employee Skills 1,Employee Skills 2,Employee Skills 3,Employee Skills 4
0,101,Johnson,Java,SQL,C++,None
1,102,Sachin,Oracle,HTML,JSP,None
2,103,Micheal,Talend,Ajax,JSP,HTML

In [ ]:
df_input = df_input.rename(columns={'emp_no':'Employee Number', 'emp_name':'Employee Name'})
df_input

,Employee Number,Employee Name,Employee Skills 1,Employee Skills 2,Employee Skills 3,Employee Skills 4
0,101,Johnson,Java,SQL,C++,None
1,102,Sachin,Oracle,HTML,JSP,None
2,103,Micheal,Talend,Ajax,JSP,HTML

In [ ]:
# Export the formatted dataframe satisfying the requirement into a CSV File
# TODO: Add your code here
df_input.to_csv('output.csv', index=False)