<a href="https://colab.research.google.com/github/shrey-shetty/v/blob/main/4_Star_Schema.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Update xlrd library
!pip install --upgrade xlrd

Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
"""
@author: Ashish Chouhan
Star Schema Creation
"""

# Import Libraries required for Processing
import pandas as pd
import numpy as np

# Setting file names used during execution process
# Input File :  Movie details and User Information Excel file consists of raw information about User
#               and Movies along with the ratings provided by User to a specific Movie
file_input = 'Movie details and User Information.xls'

# Output File : Pre-Processed Movie Lens Data CSV file will hold the information, after input file
#               is being pre-processed; so as to remove Null Value and InConsistent value.
file_pre_processed = 'Pre-Processed Movie Lens Data.csv'

# Output File : User_Details.xlsx file will hold only the User Information.
#               Movie_Details.xlsx file will hold only the Movie Information.
#               Movie_Ratings_for_Users.xlsx file will hold the factual information of
#               Movie Ratings provided by User.
file_user_output = 'User_Details.xlsx'
file_movie_output = 'Movie_Details.xlsx'
file_rating_output = 'Movie_Ratings_for_Users.xlsx'

Read Input File to fetch Raw Information of User and Ratings provided to specific movie

In [ ]:
# Read the Movie details and User Information Excel file using pandas.read_excel function and
# populate the records into an input Dataframe
# Link: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html
# TODO: Add your code here
df_input = pd.read_excel(file_input, header=0)
df_input

,User_ID,Gender,Zip_Code,Occupation,Age_Min_Value,Age_Max_Value,Movie_ID,Title,Ratings,TimeStamp,Genres
0,1.0,F,48067.0,K-12 student,0.0,17.0,1193.0,One Flew Over the Cuckoo's Nest (1975),5,978300760,Drama
1,3902.0,M,46239.0,customer service,25.0,34.0,2410.0,Rocky III (1982),5,965766922,Action|Drama
2,3902.0,M,46239.0,customer service,25.0,34.0,2411.0,Rocky IV (1985),5,965768121,Action|Drama
3,3902.0,M,46239.0,customer service,25.0,34.0,2412.0,Rocky V (1990),5,965768121,Action|Drama
4,3902.0,M,46239.0,customer service,25.0,34.0,1610.0,Hunt for Red October - The (1990),5,965765527,Action|Thriller
...,...,...,...,...,...,...,...,...,...,...,...
65530,438.0,M,53705.0,lawyer,18.0,24.0,1005.0,D3: The Mighty Ducks (1996),1,976258101,Children's|Comedy
65531,438.0,M,53705.0,lawyer,18.0,24.0,2746.0,Little Shop of Horrors (1986),5,981600179,Comedy|Horror|Musical
65532,438.0,M,53705.0,lawyer,18.0,24.0,3549.0,Guys and Dolls (1955),5,976244901,Musical
65533,438.0,M,53705.0,lawyer,18.0,24.0,10.0,GoldenEye (1995),3,980904083,Action|Adventure|Thriller
65534,438.0,M,53705.0,lawyer,18.0,24.0,333.0,Tommy Boy (1995),4,976254749,Comedy

# Pre-Processing of Input Dataframe

In [ ]:
# Replace invalid value present in the columns with NaN or Null Values
df_input['Occupation'] = df_input.Occupation.replace(11413, np.nan)
df_input['Title'] = df_input.Title.replace(1682, np.nan)
df_input['Genres'] = df_input.Genres.replace([1523648,'1 - 000 - 000 Duck (1971)'], np.nan)
df_input['Ratings'] = df_input.Ratings.replace('Super', np.nan)
df_input['TimeStamp'] = df_input.TimeStamp.replace('League of Their Own', np.nan)

# Processed Input Dataframe will now have only valid values present in column or Null Values
df_input.isna().sum()

/tmp/ipykernel_3269/3815525194.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_input['Ratings'] = df_input.Ratings.replace('Super', np.nan)
/tmp/ipykernel_3269/3815525194.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_input['TimeStamp'] = df_input.TimeStamp.replace('League of Their Own', np.nan)

User_ID          676
Gender           667
Zip_Code         670
Occupation       672
Age_Min_Value    671
Age_Max_Value    669
Movie_ID           5
Title              6
Ratings            5
TimeStamp          3
Genres             7
dtype: int64

In [ ]:
# Delete record from input dataframe (df_input) having NaN or Null Values for any of the column present in
# the dataframe
df_input.dropna(axis = 'rows', inplace = True)

df_input.isna().sum()

User_ID          0
Gender           0
Zip_Code         0
Occupation       0
Age_Min_Value    0
Age_Max_Value    0
Movie_ID         0
Title            0
Ratings          0
TimeStamp        0
Genres           0
dtype: int64

In [ ]:
# Save the Pre-Processed DataFrame into a CSV file
# TODO: Add your code here
df_input.to_csv(file_pre_processed, index=False)

# Creation of Star Schema

In [ ]:
# Read Pre-processed Movie Lens Data CSV File which is populated above using pandas.read_csv function
# and populate the records into a new dataframe (df_pre_processed)
df_pre_processed = pd.read_csv(file_pre_processed, header = 0)

df_pre_processed

,User_ID,Gender,Zip_Code,Occupation,Age_Min_Value,Age_Max_Value,Movie_ID,Title,Ratings,TimeStamp,Genres
0,1.0,F,48067.0,K-12 student,0.0,17.0,1193.0,One Flew Over the Cuckoo's Nest (1975),5.0,978300760.0,Drama
1,3902.0,M,46239.0,customer service,25.0,34.0,2410.0,Rocky III (1982),5.0,965766922.0,Action|Drama
2,3902.0,M,46239.0,customer service,25.0,34.0,2411.0,Rocky IV (1985),5.0,965768121.0,Action|Drama
3,3902.0,M,46239.0,customer service,25.0,34.0,2412.0,Rocky V (1990),5.0,965768121.0,Action|Drama
4,3902.0,M,46239.0,customer service,25.0,34.0,1610.0,Hunt for Red October - The (1990),5.0,965765527.0,Action|Thriller
...,...,...,...,...,...,...,...,...,...,...,...
64820,438.0,M,53705.0,lawyer,18.0,24.0,1005.0,D3: The Mighty Ducks (1996),1.0,976258101.0,Children's|Comedy
64821,438.0,M,53705.0,lawyer,18.0,24.0,2746.0,Little Shop of Horrors (1986),5.0,981600179.0,Comedy|Horror|Musical
64822,438.0,M,53705.0,lawyer,18.0,24.0,3549.0,Guys and Dolls (1955),5.0,976244901.0,Musical
64823,438.0,M,53705.0,lawyer,18.0,24.0,10.0,GoldenEye (1995),3.0,980904083.0,Action|Adventure|Thriller
64824,438.0,M,53705.0,lawyer,18.0,24.0,333.0,Tommy Boy (1995),4.0,976254749.0,Comedy

Split the columns as per requirement from df_pre_processed dataframe into different dataframes.

In [ ]:
# Select columns which are relevant to user information from df_pre_processed dataFrame
# and populate it into a new subset DataFrame (df_users)
df_users = df_pre_processed.loc[: , ['User_ID', 'Gender', 'Zip_Code', 'Occupation', 'Age_Min_Value', 'Age_Max_Value']]

df_users

,User_ID,Gender,Zip_Code,Occupation,Age_Min_Value,Age_Max_Value
0,1.0,F,48067.0,K-12 student,0.0,17.0
1,3902.0,M,46239.0,customer service,25.0,34.0
2,3902.0,M,46239.0,customer service,25.0,34.0
3,3902.0,M,46239.0,customer service,25.0,34.0
4,3902.0,M,46239.0,customer service,25.0,34.0
...,...,...,...,...,...,...
64820,438.0,M,53705.0,lawyer,18.0,24.0
64821,438.0,M,53705.0,lawyer,18.0,24.0
64822,438.0,M,53705.0,lawyer,18.0,24.0
64823,438.0,M,53705.0,lawyer,18.0,24.0
64824,438.0,M,53705.0,lawyer,18.0,24.0

In [ ]:
# Select columns ('Movie_ID', 'Title', 'Genres') which are relevant to movie information from df_pre_processed dataFrame
# and populate it into a new subset DataFrame (df_movies)
# TODO: Add your code here
df_movies = df_pre_processed.loc[:, ['Movie_ID','Title','Genres']]

df_movies

,Movie_ID,Title,Genres
0,1193.0,One Flew Over the Cuckoo's Nest (1975),Drama
1,2410.0,Rocky III (1982),Action|Drama
2,2411.0,Rocky IV (1985),Action|Drama
3,2412.0,Rocky V (1990),Action|Drama
4,1610.0,Hunt for Red October - The (1990),Action|Thriller
...,...,...,...
64820,1005.0,D3: The Mighty Ducks (1996),Children's|Comedy
64821,2746.0,Little Shop of Horrors (1986),Comedy|Horror|Musical
64822,3549.0,Guys and Dolls (1955),Musical
64823,10.0,GoldenEye (1995),Action|Adventure|Thriller
64824,333.0,Tommy Boy (1995),Comedy

In [ ]:
# Select columns ('User_ID', 'Movie_ID', 'Ratings', 'TimeStamp') which are relevant to factual information about Movie Rating from df_pre_processed
# dataFrame and populate it into a new subset DataFrame (df_rating)
# TODO: Add your code here
df_ratings = df_pre_processed.loc[:, ['User_ID', 'Movie_ID', 'Ratings', 'TimeStamp']]

df_ratings

       User_ID  Movie_ID  Ratings    TimeStamp
0          1.0    1193.0      5.0  978300760.0
1       3902.0    2410.0      5.0  965766922.0
2       3902.0    2411.0      5.0  965768121.0
3       3902.0    2412.0      5.0  965768121.0
4       3902.0    1610.0      5.0  965765527.0
...        ...       ...      ...          ...
64820    438.0    1005.0      1.0  976258101.0
64821    438.0    2746.0      5.0  981600179.0
64822    438.0    3549.0      5.0  976244901.0
64823    438.0      10.0      3.0  980904083.0
64824    438.0     333.0      4.0  976254749.0

[64825 rows x 4 columns]

**df_users** dataframe represent User Dimension Table,

**df_movies** dataframe represent Movie Dimension Table,

**df_ratings** represent Movie Rating Fact Table.

Requirement states that all table must have uniqe records and they must be sorted.

In [ ]:
# Sort the df_users dataframe in ascending order based on User ID
# TODO: Add your code here
df_users=df_users.sort_values(by='User_ID', ascending=True)
# Remove duplicate User ID records
# TODO: Add your code here
df_users=df_users.drop_duplicates(subset='User_ID', keep='first')
df_users

,User_ID,Gender,Zip_Code,Occupation,Age_Min_Value,Age_Max_Value
43,1.0,F,48067.0,K-12 student,0.0,17.0
118,2.0,M,70072.0,self-employed,56.0,100.0
183,3.0,M,55117.0,scientist,25.0,34.0
226,4.0,M,2460.0,executive/managerial,45.0,49.0
347,5.0,M,55455.0,writer,25.0,34.0
...,...,...,...,...,...,...
64299,436.0,M,43023.0,college/grad student,18.0,24.0
64346,437.0,M,55030.0,technician/engineer,35.0,44.0
64636,438.0,M,53705.0,lawyer,18.0,24.0
5,3902.0,M,46239.0,customer service,25.0,34.0
8,5667.0,M,10009.0,executive/managerial,35.0,44.0

In [ ]:
# Sort the df_movies dataframe in ascending order based on Movie ID and
# remove duplicate Movie ID records
# TODO: Add your code here
df_movies=df_movies.sort_values(by='Movie_ID', ascending= True)
df_movies

       Movie_ID                    Title                       Genres
34          1.0         Toy Story (1995)  Animation|Children's|Comedy
10842       1.0         Toy Story (1995)  Animation|Children's|Comedy
42232       1.0         Toy Story (1995)  Animation|Children's|Comedy
15254       1.0         Toy Story (1995)  Animation|Children's|Comedy
14939       1.0         Toy Story (1995)  Animation|Children's|Comedy
...         ...                      ...                          ...
32721    3952.0  Contender -  The (2000)               Drama|Thriller
2856     3952.0  Contender -  The (2000)               Drama|Thriller
34787    3952.0  Contender -  The (2000)               Drama|Thriller
55582    3952.0  Contender -  The (2000)               Drama|Thriller
23818    3952.0  Contender -  The (2000)               Drama|Thriller

[64825 rows x 3 columns]

In [ ]:
# Sort the df_user_movie_fact dataframe in ascending order based on User ID and Movie ID, also
# remove duplicate record for User ID and Movie ID Combination
# TODO: Add your code here
df_ratings=df_ratings.sort_values(by=['User_ID', 'Movie_ID'], ascending= True)
df_ratings=df_ratings.drop_duplicates(subset=['User_ID', 'Movie_ID'], keep='first')
df_ratings

    User_ID  Movie_ID  Ratings    TimeStamp
34      1.0       1.0      5.0  978824268.0
23      1.0      48.0      5.0  978824351.0
33      1.0     150.0      5.0  978301777.0
38      1.0     260.0      4.0  978300760.0
21      1.0     527.0      5.0  978824195.0
..      ...       ...      ...          ...
5    3902.0    2273.0      5.0  965765661.0
1    3902.0    2410.0      5.0  965766922.0
2    3902.0    2411.0      5.0  965768121.0
3    3902.0    2412.0      5.0  965768121.0
8    5667.0     364.0      5.0  958757827.0

[64824 rows x 4 columns]

# Export the Star Schema

In [ ]:
writer_user = pd.ExcelWriter(file_user_output)
df_users.to_excel(writer_user, sheet_name='Users', index=False)
writer_user.close()

In [ ]:
# Save Movie data in the 'Movies' sheet of a Excel File
# TODO: Add your code here
writer_movie = pd.ExcelWriter(file_movie_output)
df_movies.to_excel(writer_movie, sheet_name='Movies', index=False)
writer_movie.close()

In [ ]:
# Save Rating data in the 'Ratings' sheet of a Excel File
# TODO: Add your code here
writer_rating = pd.ExcelWriter(file_rating_output)
df_ratings.to_excel(writer_rating, sheet_name ='Ratings' , index=False)
writer_rating.close()

# Export to BigQuery

In [ ]:
!pip install --upgrade google-cloud-bigquery

Requirement already satisfied: google-cloud-bigquery in /usr/local/lib/python3.12/dist-packages (3.41.0)
Requirement already satisfied: google-api-core<3.0.0,>=2.11.1 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (2.30.3)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.47.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.6.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.9.0)
Requirement already satisfied: packaging>=24.2.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (26.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.32.4)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.75.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.28.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.80.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.71.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (4.9.1)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery) (1.8.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2026.5.20)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (4.15.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.6.3)

In [ ]:
# Convert column types to Integer
ratings = df_ratings.astype('int')
ratings.dtypes

User_ID      int64
Movie_ID     int64
Ratings      int64
TimeStamp    int64
dtype: object

In [ ]:
from google.cloud import bigquery
from google.cloud.exceptions import NotFound
from google.oauth2 import service_account

# Set key_path to the path to the service account key file.
# Follow this steps to generate the json file: https://cloud.google.com/bigquery/docs/quickstarts/quickstart-client-libraries
credentials = service_account.Credentials.from_service_account_file(
    "/content/my-project-1-480817-80d962e3c10a.json",
    scopes=["https://www.googleapis.com/auth/cloud-platform"],
)

client = bigquery.Client(
    credentials=credentials,
    project='13115003870',
)

dataset_id = 'data_management_2'
table_id = f"{dataset_id}.movie_ratings"

# Construct a full Dataset object to send to the API.
dataset = bigquery.Dataset(f"{client.project}.{dataset_id}")

# Specify the geographic location where the dataset should reside.
dataset.location = "US"

# Check if the dataset exists, create it if not
try:
    client.get_dataset(dataset_id)
    print(f"Dataset {dataset_id} already exists.")
except NotFound:
    print(f"Dataset {dataset_id} not found. Creating dataset...")
    dataset = client.create_dataset(dataset, timeout=30)  # Make an API request.
    print(f"Created dataset {client.project}.{dataset.dataset_id}")

# Since string columns use the "object" dtype, remember to pass in a (partial) schema to ensure the correct BigQuery data type.
# https://cloud.google.com/bigquery/docs/samples/bigquery-load-table-dataframe
job = client.load_table_from_dataframe(ratings, table_id)

# Wait for the load job to complete
job.result()

Dataset data_management_2 not found. Creating dataset...
Created dataset 13115003870.data_management_2

LoadJob<project=13115003870, location=US, id=cdbb88d3-5dca-40c1-8290-536e0a5a0d25>